os: linux
dist: bionic
language: php

stage: Build Docker Images
env:
  - PHP_BUILD_VERSION=8.0
  - PHP_BUILD_VERSION=7.4
  - PHP_BUILD_VERSION=7.3
  - PHP_BUILD_VERSION=7.2
  - PHP_BUILD_VERSION=7.1
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce    
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin && PUSH="--push"; fi
  - docker build --build-arg PHP_BUILD_VERSION=${PHP_BUILD_VERSION} -t larueli/php-symfony-base-image:${PHP_BUILD_VERSION} .
  - if [ ! -z $PUSH ]; then docker push larueli/php-symfony-base-image:${PHP_BUILD_VERSION}; fi
        
jobs:
  include:
    - stage: Deploy
      if: type != pull_request AND branch = master
      env:
        - PHP_BUILD_VERSION=7.4
      script:
        - echo "$DOCKER_HUB_TOKEN" | docker login -u larueli --password-stdin
        - docker pull larueli/php-symfony-base-image:7.4
        - docker tag larueli/php-symfony-base-image:7.4 larueli/php-symfony-base-image:latest
        - docker push larueli/php-symfony-base-image:latest
