name: Build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  
  schedule:
    - cron: '0 8 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.1','7.2','7.3','7.4','8.0']

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:${{ matrix.php-version }}
          build-args: PHP_BUILD_VERSION=${{ matrix.php-version }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push 8.0 to latest
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:8.0
          dst: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:latest
