name: Build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  schedule:
    - cron: '0 8 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1','8.2','8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push dev
        id: docker_build_dev
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:${{ matrix.php-version }}-dev
          build-args: PHP_BUILD_VERSION=${{ matrix.php-version }}-dev

      - name: Build and push prod
        id: docker_build_prod
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:${{ matrix.php-version }}
          build-args: PHP_BUILD_VERSION=${{ matrix.php-version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push 8.3 to latest
        uses: akhilerm/tag-push-action@v2.2.0
        with:
          src: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:8.3
          dst: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/php-symfony-base-image:latest
